---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "heroku"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 7
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 7
