---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 7
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 7
