---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
    reviewers:
      - "andros21"
  - package-ecosystem: "pip"
    directory: "requirements/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    reviewers:
      - "andros21"
    groups:
      pip:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
