[tool.poetry]
name = "pwrapp"
version = "0.0.0"
description = "Dash application for mcce"
authors = ["andros21 <andrea.ros21@e.email>"]
license = "GPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.24.2"
pandas = "^1.5.3"
SQLAlchemy = "^1.4.46"
dash = "^2.9.3"
gunicorn = "^20.1.0"
psycopg2-binary = "^2.9.5"

[tool.poetry.dev-dependencies]

[[tool.poetry.source]]
name    = "piwheels"
url     = "https://www.piwheels.org/simple/"
default = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
