[tool.poetry]
name        = "pwrApp"
version     = "0.0.0"
description = "Dash application for mcce"
license     = "GPL-3.0-only"
authors     = ["andros21 <andrea.ros21@e.email>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.23.4"
pandas = "^1.5.0"
plotly = "^5.1.0"
sqlalchemy = "^1.4.41"
flask = "^2.2.0"
gunicorn = "^20.1.0"
dash = "^2.6.2"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]

[[tool.poetry.source]]
name    = "piwheels"
url     = "https://www.piwheels.org/simple/"
default = true

[build-system]
requires      = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
