---
name: Heroku Deploy

"on":
  push:
    branches:
      - heroku

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy heroku
    runs-on: ubuntu-latest
    environment:
      name: heroku
      url: https://epwr-stats.herokuapp.com/
    steps:
      - name: Checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Setup python
        uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb
        with:
          python-version: 3.9
      - name: Install poetry
        uses: snok/install-poetry@2bf112a0f6979928eb6b011f39700db589c5961e
        with:
          virtualenvs-create: false
      - name: Export requirements.txt
        run: |
          poetry export --without-hashes | tail -n +3 > requirements.txt
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          buildpack: https://github.com/heroku/heroku-buildpack-python
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: epwr-stats
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          dontuseforce: true
          dontautocreate: true
          rollbackonhealthcheckfailed: true
          healthcheck: https://epwr-stats.herokuapp.com
          delay: 7
