---
name: Heroku Deploy

"on":
  push:
    branches:
      - heroku

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy heroku
    runs-on: ubuntu-latest
    environment:
      name: heroku
      url: https://epwr-stats.herokuapp.com/
    steps:
      - name: Checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          buildpack: https://github.com/heroku/heroku-buildpack-python
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: epwr-stats
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
