---
name: Heroku Deploy

"on":
  push:
    branches:
      - heroku

permissions: read-all

jobs:
  deploy:
    name: Deploy heroku
    runs-on: ubuntu-latest
    environment:
      name: heroku
      url: https://epwr-stats.herokuapp.com/
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          buildpack: https://github.com/heroku/heroku-buildpack-python
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: epwr-stats
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
